"""initial

Revision ID: 1b6bfa5d666d
Revises: 
Create Date: 2025-06-18 21:54:42.845173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b6bfa5d666d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtoken', 'revoked')
    op.drop_column('refreshtoken', 'expires_at')
    op.alter_column('user', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('refreshtoken', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('refreshtoken', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
