"""added missing refresh token stuff

Revision ID: 7649e0225c51
Revises: ce55f2b653d1
Create Date: 2025-06-18 21:56:08.832062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7649e0225c51'
down_revision: Union[str, None] = 'ce55f2b653d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('refreshtoken', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtoken', 'revoked')
    op.drop_column('refreshtoken', 'expires_at')
    # ### end Alembic commands ###
