"""removed client tags

Revision ID: cb0ddf6182de
Revises: e6b3c4f6e2ab
Create Date: 2025-06-18 23:33:14.313019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0ddf6182de'
down_revision: Union[str, None] = 'e6b3c4f6e2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clienttag_client_id'), table_name='clienttag')
    op.drop_table('clienttag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienttag',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('clienttag_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clienttag_pkey'))
    )
    op.create_index(op.f('ix_clienttag_client_id'), 'clienttag', ['client_id'], unique=False)
    # ### end Alembic commands ###
