"""added created at and updated at to documents attachment

Revision ID: dfb57d7ac751
Revises: ca89f9c01666
Create Date: 2025-06-20 21:39:07.249485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'dfb57d7ac751'
down_revision: Union[str, None] = 'ca89f9c01666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'ust_id_validated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client', 'dunning_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('document_attachment', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    op.add_column('document_attachment', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_attachment', 'updated_at')
    op.drop_column('document_attachment', 'created_at')
    op.alter_column('client', 'dunning_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'ust_id_validated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
