"""Client contact person and documents

Revision ID: e6b3c4f6e2ab
Revises: 9c62bda56fb2
Create Date: 2025-06-18 23:23:50.183106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'e6b3c4f6e2ab'
down_revision: Union[str, None] = '9c62bda56fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('client', 'prospect', 'lead', name='clienttypeenum'), nullable=False),
    sa.Column('ust_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('ust_id_validated', sa.Boolean(), nullable=False),
    sa.Column('ust_id_checked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dunning_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('clienttag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clienttag_client_id'), 'clienttag', ['client_id'], unique=False)
    op.create_table('contact_person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_main_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_person_client_id'), 'contact_person', ['client_id'], unique=False)
    op.create_index(op.f('ix_contact_person_email'), 'contact_person', ['email'], unique=False)
    op.create_index(op.f('ix_contact_person_id'), 'contact_person', ['id'], unique=False)
    op.create_table('document_attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_attachment_client_id'), 'document_attachment', ['client_id'], unique=False)
    op.create_index(op.f('ix_document_attachment_id'), 'document_attachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_attachment_id'), table_name='document_attachment')
    op.drop_index(op.f('ix_document_attachment_client_id'), table_name='document_attachment')
    op.drop_table('document_attachment')
    op.drop_index(op.f('ix_contact_person_id'), table_name='contact_person')
    op.drop_index(op.f('ix_contact_person_email'), table_name='contact_person')
    op.drop_index(op.f('ix_contact_person_client_id'), table_name='contact_person')
    op.drop_table('contact_person')
    op.drop_index(op.f('ix_clienttag_client_id'), table_name='clienttag')
    op.drop_table('clienttag')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
